services:
  - type: web
    name: backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    rootDir: backend
    envVars:
      - key: DATABASE_URL
        value: sqlite:///dev.db

  - type: web
    name: frontend
    env: static
    buildCommand: "npm install && npm run build"
    staticPublishPath: build
    rootDir: frontend
