services:
  - type: web
    name: backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: DATABASE_URL
        value: sqlite:///dev.db
    plan: free
    autoDeploy: true
    repo: https://github.com/sertacsen/import-export-app
    branch: master
    rootDir: backend

  - type: web
    name: frontend
    env: static
    buildCommand: "npm install && npm run build"
    staticPublishPath: build
    rootDir: frontend
